[project]
name = "code-blog-writing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "crewai[google-genai,tools]>=1.7.1",
    "langchain>=1.2.0",
    "langchain-community>=0.4.1",
    "python-dotenv>=1.1.1",
]
